# Generated by Django 5.0.1 on 2024-02-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nairko_app', '0003_participant_enemy_player_damage_taken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='enemy_player_total_heal',
            field=models.IntegerField(default=0),
        ),
    ]
