# Generated by Django 5.0.1 on 2024-02-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nairko_app', '0004_participant_enemy_player_total_heal'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='enemy_player_cs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='enemy_player_total_wards_placed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='enemy_team_cs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='enemy_team_total_wards_placed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='player_cs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='player_damage_mitigated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='player_total_wards_placed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='team_cs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='team_total_wards_placed',
            field=models.IntegerField(default=0),
        ),
    ]
